### ISSUE TITLE
ErrorException "Invalid JSON-RPC 2.0 response" thrown when decoding message with error object

### ISSUE THREAD

**Issue by raraworks** [datto/php-json-rpc#11]
I might be incorrect, but it seems that when decoding response from JSON RPC server, **and response contains error object**, parameter [result](https://github.com/datto/php-json-rpc/blob/4465221e4d40ffb7fdfd72a0bd86eb9a3b7a47df/src/Client.php#L219) is requested where as per [specification](https://www.jsonrpc.org/specification#response_object) it is not required:

![image](https://user-images.githubusercontent.com/18421085/52721622-bc384800-2fb2-11e9-8a3e-e2e72fb671aa.png)

And so decode fails and throws an errorException.

**Comment by smortensen** [comment]
It turns out we use the existence of the 'result' property to decide whether we're dealing with a result object or an error object.

Here's the corresponding line of code:
https://github.com/datto/php-json-rpc/blob/4465221e4d40ffb7fdfd72a0bd86eb9a3b7a47df/src/Client.php#L213-L214

So! If there is no 'result' property, then the "getResult" function will return false and we'll end up fetching an error object instead.

**Comment by raraworks** [comment]
Yes, this was correct.

The API I was connecting to, was not sending correct error object structure (error code was not an integer).

You are completely correct, thanks for clarification.
