### ISSUE TITLE
Support for passing additional arguments to evaluators

### ISSUE THREAD

**Issue by jmccaffrey42** [datto/php-json-rpc#9]
I'm writing a PR for a feature that allows you to pass some additional arguments to reply(). The goal of this feature is to allow passing context to the RPC method such as (in my case) websocket caller information. 

**Use-case**: Lets say I'm building a chat app with WebSocket and I'm using JSON-RPC messages as the protocol between the client and server. If the client calls sendMessage with some arguments like ["this is a message"], the ChatRoom\sendMessage function the server side needs to know how to relay the message back to the other clients. In this case, if all method calls contained a $clientContext, the ChatRoom class can keep state of who is in the room and what their $clientContext is. This would allow the sendMessage method to iterate over a list of clients and send messages to them as part of its business logic.

**API change**: This change would add a new optional parameter to reply such as $server->reply($clientMessage, array($clientContext)) and this new list of arguments would be appended to the arguments passed by the client already.

I want to gather some feedback on this idea before I fully lock down the code and submit the PR, what do you think?

**Comment by spencer-mortensen** [comment]
Hi Jonathan,

Thank you for your proposal and pull request.

To check my understanding: We're implementing a chat room. On the server, there is a "ChatRoom" object that will respond to JSON-RPC requests as they arrive over a WebSocket. The JSON-RPC method and its arguments alone are not enough: The "ChatRoom" also needs some state information along with every request.

Now, ordinarily, we might expect the "ChatRoom" class to have a method that can be used to set the context. That method might be the constructor ("$chatRoom = new ChatRoom($context);"), or it might be a separate method ("$chatRoom->setContext($context);"). Either way, the "ChatRoom" would be set up in advance, so that the server is ready to evaluate the JSON-RPC messages as they arrive from the client.

Would that work? Or is the context something that will change over time as we receive messages from the client? If that's the trouble--the context could change with each message--then here's an alternative:

The context is legitimately part of the request, so it should appear in the arguments payload that is sent by the client. The client would be responsible for inserting the context into the arguments list that is building for the request. That way, the evaluator has the full information that it needs to process the request.

Would that work? Or is the context really metadata that needs to sent along with every message in exactly the same way, so we'd like to keep it separate from the method-specific arguments? If that's case--the context is really metadata that should remain separate--then here's an alternative:

The method-specific arguments could be wrapped up inside a larger package. If the original arguments list looked like this: '"params": [1, 2, 3]' then the augmented arguments list could like this: '"params": {"context": ..., "arguments": [1, 2, 3]}'. The evaluator would unpackage the data, making a note of the context, and would send the method-specific arguments off for evaluation.

Would that work? I feel like these kinds of extensions are how JSON-RPC was envisioned to work. It's a beautiful system! On the other hand, I don't know the details of the situation that you're facing.

Let me know what you're thinking.

~Spencer

**Comment by spencer-mortensen** [comment]
Hi Jonathan,

Did that make sense? Or did I misunderstand what you were saying?

~Spencer

**Comment by smortensen** [comment]
Well, I still don't understand the use case for this, and I haven't heard back from the original author, so I'm going to close this pull request.
